// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-F3P-WtDG8BQa5-YkZ3FvX5zWkOz0mb4',
    appId: '1:954758485183:web:8dcfb1c3a1b7709ca6e20a',
    messagingSenderId: '954758485183',
    projectId: 'group-task-a30ee',
    authDomain: 'group-task-a30ee.firebaseapp.com',
    storageBucket: 'group-task-a30ee.appspot.com',
    measurementId: 'G-2060DDQY75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeX2t0Z9mkLtLN_hkY0Vy3vBnZH5oQXlQ',
    appId: '1:954758485183:android:374e5a84ebaa0434a6e20a',
    messagingSenderId: '954758485183',
    projectId: 'group-task-a30ee',
    storageBucket: 'group-task-a30ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5pg-086ziTt2noFNnD0hO_euBp5JBVW8',
    appId: '1:954758485183:ios:34b3b3dc482f3f23a6e20a',
    messagingSenderId: '954758485183',
    projectId: 'group-task-a30ee',
    storageBucket: 'group-task-a30ee.appspot.com',
    iosClientId: '954758485183-aqo6mnta5geh72t71hn2g5fc58coq1d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.workmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5pg-086ziTt2noFNnD0hO_euBp5JBVW8',
    appId: '1:954758485183:ios:34b3b3dc482f3f23a6e20a',
    messagingSenderId: '954758485183',
    projectId: 'group-task-a30ee',
    storageBucket: 'group-task-a30ee.appspot.com',
    iosClientId: '954758485183-aqo6mnta5geh72t71hn2g5fc58coq1d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.workmanager',
  );
}
